name: 🎽 CI

on:
  push:
    branches:
      - main
    paths:
      - "**.astro"
      - "**.ts"
      - "**.snap"
      - bun.lock
      - .github/workflows/ci.yml
  pull_request:
    paths:
      - "**.astro"
      - "**.ts"
      - "**.snap"
      - bun.lock
      - .github/workflows/ci.yml

permissions: {}

jobs:
  astro-check:
    name: 🚀 Astro Check
    runs-on: Ubuntu-Slim
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with cache
        uses: 5ouma/utils/setup-bun-with-cache@e7cf7a62cbf6353c7b9667884a54d9a3e93ae2af # v0.9.4

      - name: 👾 Create meta file
        run: cp meta.example.json meta.json

      - name: 🚀 Astro check
        run: bun run check:astro

  biome-check:
    name: 🏞️ Biome Check
    runs-on: Ubuntu-Slim
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with Cache
        uses: 5ouma/utils/setup-bun-with-cache@e7cf7a62cbf6353c7b9667884a54d9a3e93ae2af # v0.9.4

      - name: 🏞️ Biome check
        run: bun run check:biome

  test:
    name: 🧪 Test
    runs-on: Ubuntu-Slim
    environment:
      name: CI
      deployment: false
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with cache
        uses: 5ouma/utils/setup-bun-with-cache@e7cf7a62cbf6353c7b9667884a54d9a3e93ae2af # v0.9.4

      - name: 👾 Create meta file
        run: cp meta.example.json meta.json

      - name: 🧪 Run tests
        run: bun run test:cov

      - name: ☂️ Upload coverage
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: ☂️ Upload test results
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results

  build-check:
    name: 🛠️ Build Check
    runs-on: Ubuntu-Slim
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with cache
        uses: 5ouma/utils/setup-bun-with-cache@e7cf7a62cbf6353c7b9667884a54d9a3e93ae2af # v0.9.4

      - name: 👾 Create meta file
        run: cp meta.example.json meta.json

      - name: 🛠️ Build check
        run: bun run build
