name: 🎽 CI

on:
  push:
    branches:
      - main
    paths:
      - "**.astro"
      - "**.ts"
      - "**.snap"
      - bun.lock
      - .github/workflows/ci.yml
  pull_request:
    paths:
      - "**.astro"
      - "**.ts"
      - "**.snap"
      - bun.lock
      - .github/workflows/ci.yml

permissions: {}

jobs:
  astro-check:
    name: 🚀 Astro Check
    runs-on: Ubuntu-Latest
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with cache
        uses: 5ouma/utils/setup-bun-with-cache@311e27d5690f66c3dcb1826578cadecb13948212 # v0.7.0

      - name: 👾 Create meta file
        run: echo "$meta" >meta.json
        env:
          meta: ${{ vars.META_TEST_FILE }}

      - name: 🚀 Astro check
        run: bun run check:astro

  biome-check:
    name: 🏞️ Biome Check
    runs-on: Ubuntu-Latest
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with Cache
        uses: 5ouma/utils/setup-bun-with-cache@311e27d5690f66c3dcb1826578cadecb13948212 # v0.7.0

      - name: 🏞️ Biome check
        run: bun run check:biome

  test:
    name: 🧪 Test
    runs-on: Ubuntu-Latest
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with cache
        uses: 5ouma/utils/setup-bun-with-cache@311e27d5690f66c3dcb1826578cadecb13948212 # v0.7.0

      - name: 👾 Create meta file
        run: echo "$meta" >meta.json
        env:
          meta: ${{ vars.META_TEST_FILE }}

      - name: 🧪 Run tests
        run: bun run test:cov

      - name: ☂️ Upload coverage
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: ☂️ Upload test results
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build-check:
    name: 🛠️ Build Check
    runs-on: Ubuntu-Latest
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with cache
        uses: 5ouma/utils/setup-bun-with-cache@311e27d5690f66c3dcb1826578cadecb13948212 # v0.7.0

      - name: 👾 Create meta file
        run: echo "$meta" >meta.json
        env:
          meta: ${{ vars.META_TEST_FILE }}

      - name: 🛠️ Build check
        run: bun run build
